ALTER TABLE materia_encuentros
ADD COLUMN IF NOT EXISTS plataforma TEXT,
ADD COLUMN IF NOT EXISTS link TEXT,
ADD COLUMN IF NOT EXISTS "linkGrabacion" TEXT,
ADD COLUMN IF NOT EXISTS "materiaId" TEXT,
ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'programado';
