// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Purge ONLY session tokens from OLD Supabase projects.
 * Tokens from the CURRENT project are preserved so the user stays logged in.
 * Supabase stores auth tokens under keys like: sb-{projectRef}-auth-token
 */
function purgeStaleSession(currentUrl: string) {
  if (typeof window === 'undefined') return;
  try {
    // Extract project ref from URL, e.g. "wdseqguetcgibafibzax" from "https://wdseqguetcgibafibzax.supabase.co"
    const match = currentUrl.match(/https:\/\/([^.]+)\.supabase\.co/);
    const currentRef = match?.[1];
    if (!currentRef) return;

    const keysToRemove: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      // Only remove sb-* keys that belong to a DIFFERENT project
      if (key && key.startsWith('sb-') && !key.startsWith(`sb-${currentRef}-`)) {
        keysToRemove.push(key);
      }
    }
    if (keysToRemove.length > 0) {
      console.info('[Supabase] Purging stale session keys from old projects:', keysToRemove);
      keysToRemove.forEach(k => localStorage.removeItem(k));
    }
  } catch (e) {
    console.warn('[Supabase] Could not purge stale sessions:', e);
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  // Accept both ANON_KEY (standard) and PUBLISHABLE_KEY (legacy) for compatibility
  const SUPABASE_ANON_KEY =
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_ANON_KEY ? ['VITE_SUPABASE_ANON_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Check your .env file.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Purge tokens from OLD projects only — preserve current project's session
  purgeStaleSession(SUPABASE_URL);

  console.info(`[Supabase] Connecting to: ${SUPABASE_URL}`);

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true, // Handle OAuth callback tokens in URL
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
